version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: card_game_postgres
    restart: always
    environment:
      POSTGRES_DB: card_game_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d card_game_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/data/db

  card_game_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/card_game_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: